<a href="https://colab.research.google.com/github/AlkaidCheng/example/blob/master/ConstructResonantLimitTable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import glob
import pandas as pd
import numpy as np

In [ ]:
base_path = "figures/results/20210821/spin0"

input_names = {
    "bbbb": "upperlimit_xsec_spin0_json_obs_fullcorr_bbbb.csv",
    "bbtautau": "upperlimit_xsec_spin0_json_obs_fullcorr_bbtautau.csv",
    "bbyy": "upperlimit_xsec_spin0_json_obs_fullcorr_bbyy.csv",    
    "combined": "upperlimit_xsec_spin0_json_obs_fullcorr_combined.csv"
}

input_paths = {}
for channel in input_names:
    input_paths[channel] = os.path.join(base_path, input_names[channel])

label_map = {
    "bbbb": r"$b\bar{b}b\bar{b}$",
    "bbtautau": r"$b\bar{b}\tau\tau$",    
    "bbyy": r"$b\bar{b}\gamma\gamma$",
    "combined": r"combined",
}

scalings = {
    "bbbb": 1000,
    "bbtautau": 1000,    
    "bbyy": 1000,
    "combined": 1
}

In [ ]:
df = {}
available_masses = set()
for channel in input_paths:
    df[channel] = pd.read_csv(input_paths[channel]).set_index('parameter')
    available_masses |= set(df[channel].index.values)
available_masses = sorted(list(available_masses))

In [ ]:
limits = []
for mass in available_masses:
    data = {}
    for channel in df:
        if mass in df[channel].index:
            data[(channel, 'exp')] = df[channel].loc[mass]['xsec_exp_NP_profiled']*scalings[channel]
            data[(channel, 'obs')] = df[channel].loc[mass]['xsec_obs_NP_profiled']*scalings[channel]
        else:
            data[(channel, 'exp')] = None
            data[(channel, 'exp')] = None
    limits.append(data)
limits_df = pd.DataFrame(limits, index=available_masses)

In [ ]:
limits_df

,"(bbbb, exp)","(bbbb, obs)","(bbtautau, exp)","(bbtautau, obs)","(bbyy, exp)","(bbyy, obs)","(combined, exp)","(combined, obs)"
251.0,2981.665909,3734.666052,348.761554,647.121476,217.711335,385.368015,177.851919,410.071265
260.0,6046.537664,8414.323837,743.966951,922.044322,372.389724,640.571192,328.488269,586.820681
270.0,NaN,NaN,NaN,NaN,391.781029,594.934747,391.781029,594.934747
280.0,4267.506921,7741.364029,841.153562,486.114472,374.266834,331.412490,328.443887,237.506830
290.0,NaN,NaN,NaN,NaN,350.084473,241.398640,350.084473,241.398640
300.0,2544.928418,3479.798297,653.195027,520.708005,372.968711,354.605425,311.512511,274.449463
312.5,NaN,NaN,NaN,NaN,364.852646,402.967902,NaN,NaN
325.0,NaN,NaN,469.360436,329.554925,333.419461,251.982868,259.988770,171.968479
337.5,NaN,NaN,NaN,NaN,293.184814,260.819496,NaN,NaN
350.0,652.752040,390.875715,354.148105,229.652548,273.311961,348.459686,193.982813,150.566182
375.0,NaN,NaN,221.477010,129.731610,240.656719,414.941471,NaN,NaN
400.0,267.036650,163.230321,147.027908,81.766454,189.665706,204.733606,100.533157,59.083751
425.0,NaN,NaN,NaN,NaN,163.446888,182.278943,NaN,NaN
450.0,NaN,NaN,68.419567,49.527178,146.078265,133.635603,58.532771,42.822343
475.0,NaN,NaN,NaN,NaN,144.349332,141.884635,NaN,NaN
500.0,94.313803,85.301486,43.327148,46.627742,129.842338,173.439677,36.014396,40.650313
550.0,NaN,NaN,33.613946,25.580588,95.159467,87.575860,30.097454,23.126331
600.0,45.422915,26.377119,26.375462,22.592422,81.081775,74.082441,20.661613,13.403142
700.0,24.590730,22.145884,19.153216,25.922559,76.457413,49.325752,14.170145,15.105191
800.0,15.884387,12.031099,15.600162,31.648265,65.787928,72.231080,10.477871,14.196613
900.0,11.050550,11.877598,13.601676,32.449911,45.766531,77.130933,8.000952,16.134913
1000.0,8.115743,6.703210,12.408774,32.287410,50.133706,51.803274,6.426184,10.509207
1100.0,6.146704,14.072667,13.672595,28.608683,NaN,NaN,5.500365,15.098336
1200.0,5.205450,9.402892,13.813647,25.081810,NaN,NaN,4.788682,10.179068
1300.0,4.486996,5.900941,NaN,NaN,NaN,NaN,4.486996,5.900941
1400.0,3.854275,7.961443,19.895431,26.874501,NaN,NaN,3.756684,8.108211
1500.0,3.382945,7.601893,NaN,NaN,NaN,NaN,3.382945,7.601893
1600.0,3.204447,5.421754,29.514161,33.441038,NaN,NaN,3.172661,5.464669
1800.0,2.496997,3.467243,NaN,NaN,NaN,NaN,2.496997,3.467243
2000.0,2.028482,2.967948,NaN,NaN,NaN,NaN,2.028482,2.967948
2500.0,1.482576,2.060087,NaN,NaN,NaN,NaN,1.482576,2.060087
3000.0,1.228952,1.215299,NaN,NaN,NaN,NaN,1.228952,1.215299

In [ ]:
limits_df_transpose = limits_df.transpose()

In [ ]:
limits_df_transpose

,251.0,260.0,270.0,280.0,290.0,300.0,312.5,325.0,337.5,350.0,...,1100.0,1200.0,1300.0,1400.0,1500.0,1600.0,1800.0,2000.0,2500.0,3000.0
"(bbbb, exp)",2981.665909,6046.537664,NaN,4267.506921,NaN,2544.928418,NaN,NaN,NaN,652.752040,...,6.146704,5.205450,4.486996,3.854275,3.382945,3.204447,2.496997,2.028482,1.482576,1.228952
"(bbbb, obs)",3734.666052,8414.323837,NaN,7741.364029,NaN,3479.798297,NaN,NaN,NaN,390.875715,...,14.072667,9.402892,5.900941,7.961443,7.601893,5.421754,3.467243,2.967948,2.060087,1.215299
"(bbtautau, exp)",348.761554,743.966951,NaN,841.153562,NaN,653.195027,NaN,469.360436,NaN,354.148105,...,13.672595,13.813647,NaN,19.895431,NaN,29.514161,NaN,NaN,NaN,NaN
"(bbtautau, obs)",647.121476,922.044322,NaN,486.114472,NaN,520.708005,NaN,329.554925,NaN,229.652548,...,28.608683,25.081810,NaN,26.874501,NaN,33.441038,NaN,NaN,NaN,NaN
"(bbyy, exp)",217.711335,372.389724,391.781029,374.266834,350.084473,372.968711,364.852646,333.419461,293.184814,273.311961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(bbyy, obs)",385.368015,640.571192,594.934747,331.412490,241.398640,354.605425,402.967902,251.982868,260.819496,348.459686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(combined, exp)",177.851919,328.488269,391.781029,328.443887,350.084473,311.512511,NaN,259.988770,NaN,193.982813,...,5.500365,4.788682,4.486996,3.756684,3.382945,3.172661,2.496997,2.028482,1.482576,1.228952
"(combined, obs)",410.071265,586.820681,594.934747,237.506830,241.398640,274.449463,NaN,171.968479,NaN,150.566182,...,15.098336,10.179068,5.900941,8.108211,7.601893,5.464669,3.467243,2.967948,2.060087,1.215299

In [ ]:
def round_sigfig(x, p):
    x_positive = np.where(np.isfinite(x) & (x != 0), np.abs(x), 10**(p-1))
    mags = 10 ** (p - 1 - np.floor(np.log10(x_positive)))
    return np.round(x * mags) / mags

def array2string(x, p=3, width=6, separator=' & ', prefix='', suffix='', nanstr=''):
    x = round_sigfig(x, p)
    str_x = []
    for num in x:
        if np.isnan(num):
            s = nanstr
        elif num.is_integer():
            s = prefix + str(int(num)) + suffix
        else:
            s = prefix + str(num) + suffix
        s = ("{:^"+str(width)+"}").format(s)
        str_x.append(s)
    return separator.join(str_x)

def get_mass_text(masses):
    text = r'{\makecell{Mass\\{[}GeV{]}}}'
    text += ' & '
    text += ' & '.join(["{:.1f}".format(m) for m in masses])
    text += r' \\'
    return text

def get_limit_text(data, indent=2):
    text = ''
    categories = data.index.values
    midrule_flag = False
    for category in categories:
        text += '\t'*indent
        channel = category[0]
        exp_or_obs = category[1]
        label = label_map[channel]
        if channel == 'combined' and not midrule_flag:
            text += r'\midrule' + '\n'
            midrule_flag = True
        if exp_or_obs == 'exp':
            text += '\multirow{{2}}{{*}}{{{}}}'.format(label)
        text += ' & '
        limits = data.loc[[category]].values[0]
        if exp_or_obs == 'exp':
            text += array2string(limits)
        elif exp_or_obs == 'obs':
            text += array2string(limits, prefix='(', suffix=')')
        text += (r' \\ ' + '\n')
    return text

def create_latex_tables(data, label='', caption=''):
    masses = data.keys().values
    preamble = '{c|' + 'c'*len(masses) + '}'
    print(r'\begin{table}[htbp]')
    print('\t' + r'\centering')
    print('\t' + r'\begin{tabular}' + preamble)
    print('\t'*2 + r'\toprule')
    print('\t'*2 + get_mass_text(masses))
    print('\t'*2 + r'\midrule')
    print(get_limit_text(table_3_df, indent=2))
    print('\t'*2 + r'\bottomrule')
    print('\t' + r'\end{tabular}')
    print(caption)
    print('\t'+ label)
    print(r'\end{table}')

In [ ]:
masses = limits_df_transpose.keys()
table_1_df = limits_df_transpose.loc[:, masses <= 350]
table_2_df = limits_df_transpose.loc[:, (350 < masses) & (masses <= 800)]
table_3_df = limits_df_transpose.loc[:, (800 < masses) & (masses <= 3000)]

In [ ]:
caption = \
r"""
\caption{Individual and combined limits for a spin-0 resonance in \si{\fb}. 
         Blank indicates no result at the mass point for the channel is available/considered.
         \bbyy is expected to dominate in the region $\le \SI{350}{\GeV}$; 
         \bbtautau is expected to dominate in $\SI{350}{\GeV}$--$\SI{800}{\GeV}$; 
         \bbbb is dominated in $\ge \SI{900}{\GeV}$. 
         If for a given mass point a single analysis limit is available, this is included in the combination only if the mass point falls in the mass region dominated by that analysis.}
"""

label = r'\label{tab:spin-0-individual-fullcorr}'
create_latex_tables(table_1_df, label=label, caption=caption)

\begin{table}[htbp]
	\centering
	\begin{tabular}{c|cccccccccc}
		\toprule
		{\makecell{Mass\\{[}GeV{]}}} & 251.0 & 260.0 & 270.0 & 280.0 & 290.0 & 300.0 & 312.5 & 325.0 & 337.5 & 350.0 \\
		\midrule
		\multirow{2}{*}{$b\bar{b}b\bar{b}$} &  11.1  &  8.12  &  6.15  &  5.21  &  4.49  &  3.85  &  3.38  &  3.2   &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (11.9) & (6.7)  & (14.1) & (9.4)  & (5.9)  & (7.96) & (7.6)  & (5.42) & (3.47) & (2.97) & (2.06) & (1.22) \\
		\multirow{2}{*}{$b\bar{b}\tau\tau$} &  13.6  &  12.4  &  13.7  &  13.8  &        &  19.9  &        &  29.5  &        &        &        &        \\
		 & (32.4) & (32.3) & (28.6) & (25.1) &        & (26.9) &        & (33.4) &        &        &        &        \\
		\multirow{2}{*}{$b\bar{b}\gamma\gamma$} &  45.8  &  50.1  &        &        &        &        &        &        &        &        &        &        \\
		 & (77.1) & (51.8) &        &        &        &        &        &        &        &        &        &        \\
		\midrule
\multirow{2}{*}{combined} &   8    &  6.43  &  5.5   &  4.79  &  4.49  &  3.76  &  3.38  &  3.17  &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (16.1) & (10.5) & (15.1) & (10.2) & (5.9)  & (8.11) & (7.6)  & (5.46) & (3.47) & (2.97) & (2.06) & (1.22) \\

		\bottomrule
	\end{tabular}

\caption{Individual and combined limits for a spin-0 resonance in \si{\fb}.
         Blank indicates no result at the mass point for the channel is available/considered.
         \bbyy is expected to dominate in the region $\le \SI{350}{\GeV}$;
         \bbtautau is expected to dominate in $\SI{350}{\GeV}$--$\SI{800}{\GeV}$;
         \bbbb is dominated in $\ge \SI{900}{\GeV}$.
         If for a given mass point a single analysis limit is available, this is included in the combination only if the mass point falls in the mass region dominated by that analysis.}

	\label{tab:spin-0-individual-fullcorr}
\end{table}

In [ ]:
caption = \
r"""
\caption{Individual and combined limits for a spin-0 resonance in \si{\fb}. 
         Blank indicates no result at the mass point for the channel is available/considered.
         \bbyy is expected to dominate in the region $\le \SI{350}{\GeV}$; 
         \bbtautau is expected to dominate in $\SI{350}{\GeV}$--$\SI{800}{\GeV}$; 
         \bbbb is dominated in $\ge \SI{900}{\GeV}$. 
         If for a given mass point a single analysis limit is available, this is included in the combination only if the mass point falls in the mass region dominated by that analysis.}
"""

label = r'\label{tab:spin-0-individual-fullcorr}'
create_latex_tables(table_2_df, label=label, caption=caption)

\begin{table}[htbp]
	\centering
	\begin{tabular}{c|cccccccccc}
		\toprule
		{\makecell{Mass\\{[}GeV{]}}} & 375.0 & 400.0 & 425.0 & 450.0 & 475.0 & 500.0 & 550.0 & 600.0 & 700.0 & 800.0 \\
		\midrule
		\multirow{2}{*}{$b\bar{b}b\bar{b}$} &  11.1  &  8.12  &  6.15  &  5.21  &  4.49  &  3.85  &  3.38  &  3.2   &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (11.9) & (6.7)  & (14.1) & (9.4)  & (5.9)  & (7.96) & (7.6)  & (5.42) & (3.47) & (2.97) & (2.06) & (1.22) \\
		\multirow{2}{*}{$b\bar{b}\tau\tau$} &  13.6  &  12.4  &  13.7  &  13.8  &        &  19.9  &        &  29.5  &        &        &        &        \\
		 & (32.4) & (32.3) & (28.6) & (25.1) &        & (26.9) &        & (33.4) &        &        &        &        \\
		\multirow{2}{*}{$b\bar{b}\gamma\gamma$} &  45.8  &  50.1  &        &        &        &        &        &        &        &        &        &        \\
		 & (77.1) & (51.8) &        &        &        &        &        &        &        &        &        &        \\
		\midrule
\multirow{2}{*}{combined} &   8    &  6.43  &  5.5   &  4.79  &  4.49  &  3.76  &  3.38  &  3.17  &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (16.1) & (10.5) & (15.1) & (10.2) & (5.9)  & (8.11) & (7.6)  & (5.46) & (3.47) & (2.97) & (2.06) & (1.22) \\

		\bottomrule
	\end{tabular}
	\label{tab:spin-0-individual-fullcorr}
\end{table}

In [ ]:
caption = \
r"""
\caption{Individual and combined limits for a spin-0 resonance in \si{\fb}. 
         Blank indicates no result at the mass point for the channel is available/considered.
         \bbyy is expected to dominate in the region $\le \SI{350}{\GeV}$; 
         \bbtautau is expected to dominate in $\SI{350}{\GeV}$--$\SI{800}{\GeV}$; 
         \bbbb is dominated in $\ge \SI{900}{\GeV}$. 
         If for a given mass point a single analysis limit is available, this is included in the combination only if the mass point falls in the mass region dominated by that analysis.}
"""

label = r'\label{tab:spin-0-individual-fullcorr}'
create_latex_tables(table_3_df, label=label, caption=caption)

\begin{table}[htbp]
	\centering
	\begin{tabular}{c|cccccccccccc}
		\toprule
		{\makecell{Mass\\{[}GeV{]}}} & 900.0 & 1000.0 & 1100.0 & 1200.0 & 1300.0 & 1400.0 & 1500.0 & 1600.0 & 1800.0 & 2000.0 & 2500.0 & 3000.0 \\
		\midrule
		\multirow{2}{*}{$b\bar{b}b\bar{b}$} &  11.1  &  8.12  &  6.15  &  5.21  &  4.49  &  3.85  &  3.38  &  3.2   &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (11.9) & (6.7)  & (14.1) & (9.4)  & (5.9)  & (7.96) & (7.6)  & (5.42) & (3.47) & (2.97) & (2.06) & (1.22) \\
		\multirow{2}{*}{$b\bar{b}\tau\tau$} &  13.6  &  12.4  &  13.7  &  13.8  &        &  19.9  &        &  29.5  &        &        &        &        \\
		 & (32.4) & (32.3) & (28.6) & (25.1) &        & (26.9) &        & (33.4) &        &        &        &        \\
		\multirow{2}{*}{$b\bar{b}\gamma\gamma$} &  45.8  &  50.1  &        &        &        &        &        &        &        &        &        &        \\
		 & (77.1) & (51.8) &        &        &        &        &        &        &        &        &        &        \\
		\midrule
\multirow{2}{*}{combined} &   8    &  6.43  &  5.5   &  4.79  &  4.49  &  3.76  &  3.38  &  3.17  &  2.5   &  2.03  &  1.48  &  1.23  \\
		 & (16.1) & (10.5) & (15.1) & (10.2) & (5.9)  & (8.11) & (7.6)  & (5.46) & (3.47) & (2.97) & (2.06) & (1.22) \\

		\bottomrule
	\end{tabular}
	\label{tab:spin-0-individual-fullcorr}
\end{table}